name: deploy terrraform code

on:
  push:
    branches:
       - main

jobs:
   deploy:  
     runs-on: ubuntu-latest
     steps:
       - name: checkout code
         uses: actions/checkout@v3

       - name: set up AWS credentials
         uses: aws-action/configure-aws-credential@v6.1.0
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
           aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY}}
           aws-region: us-east-1

       - name: set up Terrraform
         uses: hashicorp/set-terraform@v1

       - name: Initialize Terrraform
         run:  terraform init 

       - name: Validate Terrraform configuration
         run:  terraform validate 

       - name: plan Terrraform deployment 
         run:  terraform plan

       - name: Apply Terrraform configuration 
         run:  terraform apply -auto-approve 